### ISSUE TITLE
/gamerule doesn't recognize new gamerules in server.

### ISSUE THREAD

**Issue by BlazeRuler** [MisterPeModder/CustomGamerules#1]
On my dedicated server, I tried to use the /gamerule command to do the command "/gamerule doInsomnia false" and it just responds with "Incorrect argument for command" with red text and a line underneath the doInsomnia false.
I am currently running on Snapshot 19w09a and i've tested it with Singleplayer and its working perfectly on there.
![2019-03-13_20 19 33](https://user-images.githubusercontent.com/23558964/54322990-b5125300-45cd-11e9-9bcb-da61bd68171e.png)
![2019-03-13_20 19 44](https://user-images.githubusercontent.com/23558964/54322991-b5125300-45cd-11e9-9d61-40da7ed7160e.png)

**Comment by MisterPeModder** [comment]
Ok, that should fix the issue, I'll roll an update soon

**Comment by MisterPeModder** [comment]
Uploaded on [curseforge](https://minecraft.curseforge.com/projects/customgamerules-api/files/2687362).
